### ISSUE TITLE
DateTime adapter not working

### ISSUE THREAD

**Issue by carlosignaciom** [WTIOAddons/date-time-adapter#13]
Since yesterday evening most of my rules using this addon, updated to the last version are not working, I see this error in the logs a lot of times

2022-11-11 09:43:50.090 INFO   : date-time-adapter: config.py:35 ERROR Strange config:searchReplaceComas() takes 2 positional arguments but 3 were given
2022-11-11 09:43:50.092 INFO   : date-time-adapter: Traceback (most recent call last):
2022-11-11 09:43:50.094 INFO   : date-time-adapter:   File "/home/pi/.webthings/addons/date-time-adapter/pkg/config.py", line 27, in load
2022-11-11 09:43:50.095 INFO   : date-time-adapter:     self.searchReplaceComas(self, config)  # Replace comma w dot
2022-11-11 09:43:50.097 INFO   : date-time-adapter: TypeError: searchReplaceComas() takes 2 positional arguments but 3 were given
2022-11-11 09:43:50.098 INFO   : date-time-adapter: EXECPTION
2022-11-11 09:43:50.100 INFO   : date-time-adapter: can only update value with string or number
2022-11-11 09:43:50.101 INFO   : date-time-adapter: ('can only update value with string or number',)
2022-11-11 09:43:50.103 INFO   : date-time-adapter: ['Traceback (most recent call last):\n', '  File "/home/pi/.webthings/addons/date-time-adapter/main.py", line 41, in <module>\n    _ADAPTER = DateTimeAdapter(verbose=_DEBUG)\n', '  File "/home/pi/.webthings/addons/date-time-adapter/pkg/date_adapter.py", line 24, in __init__\n    self.start_pairing(1)\n', '  File "/home/pi/.webthings/addons/date-time-adapter/pkg/date_adapter.py", line 42, in start_pairing\n    self._config))\n', '  File "/home/pi/.webthings/addons/date-time-adapter/pkg/date_device.py", line 76, in __init__\n    _config.horizon)\n', '  File "/home/pi/.webthings/addons/date-time-adapter/pkg/util.py", line 22, in __init__\n    self.next_sunrise = self.calc_sunrise()\n', '  File "/home/pi/.webthings/addons/date-time-adapter/pkg/util.py", line 125, in calc_sunrise\n    observer_today = self.get_observer()\n', '  File "/home/pi/.webthings/addons/date-time-adapter/pkg/util.py", line 106, in get_observer\n    observer_today.horizon = self.horizon\n', 'TypeError: can only update value with string or number\n']

**Comment by carlosignaciom** [comment]
![image](https://user-images.githubusercontent.com/3088942/201306682-d21207f2-94b5-4f2d-bd4c-114665ecdef4.png)

**Comment by wfahle** [comment]
My apologies, 1.2.2 fixes this issue, but the addons-list pull request will have to be resolved to get it live. In the mean time you can manually add 1.2.2. Sorry about that. I made what looked to be a small change but it has had big ramifications. Once this is fixed I doubt I will be able to continue to maintain this code because I don't have an adequate test harness for it at the moment.

**Comment by carlosignaciom** [comment]
Good evening:
Thanks so much for patching the code that fast, first of all.
Unfortunately the patch seems is not working
I managed to install manually the new version, but I'm still unable to use it in my gateway.  I see this error in the logs:

2022-11-12 00:09:49.512 INFO   : Loading add-on: date-time-adapter
2022-11-12 00:09:50.207 ERROR  : date-time-adapter: Traceback (most recent call last):
2022-11-12 00:09:50.209 ERROR  : date-time-adapter:   File "/home/pi/.webthings/addons/date-time-adapter/main.py", line 13, in <module>
2022-11-12 00:09:50.210 ERROR  : date-time-adapter:     from pkg.date_adapter import DateTimeAdapter  # noqa
2022-11-12 00:09:50.212 ERROR  : date-time-adapter:   File "/home/pi/.webthings/addons/date-time-adapter/pkg/date_adapter.py", line 8, in <module>
2022-11-12 00:09:50.214 ERROR  : date-time-adapter:     from .date_device import DateTimeDevice  # , DateTimeTestDevice
2022-11-12 00:09:50.216 ERROR  : date-time-adapter:   File "/home/pi/.webthings/addons/date-time-adapter/pkg/date_device.py", line 9, in <module>
2022-11-12 00:09:50.217 ERROR  : date-time-adapter:     from .util import DT
2022-11-12 00:09:50.219 ERROR  : date-time-adapter:   File "/home/pi/.webthings/addons/date-time-adapter/pkg/util.py", line 4, in <module>
2022-11-12 00:09:50.221 ERROR  : date-time-adapter:     import ephem
2022-11-12 00:09:50.222 ERROR  : date-time-adapter:   File "/home/pi/.webthings/addons/date-time-adapter/lib/ephem/__init__.py", line 5, in <module>
2022-11-12 00:09:50.224 ERROR  : date-time-adapter:     import ephem._libastro as _libastro
2022-11-12 00:09:50.226 ERROR  : date-time-adapter: ModuleNotFoundError: No module named 'ephem._libastro'

I've tried to re add DateTimeAdapter to my things list, but I can't do it. I previously removed the addon and the thing to rewrite my rules without using this addon.

Also, If I try to change the lat I receive an "undefined" 400 error.

Thanks in advance for your time.

**Comment by carlosignaciom** [comment]
It's working with the 1.2.3 version!! Thanks so much

**Comment by hwine** [comment]
@wfahle Since v1.2.3 seems to be working, could you make a PR for it, please? (like the [1.2.2 PR](https://github.com/WebThingsIO/addon-list/pull/1480/)

@carlosignaciom - how did you install manually? I can't find the directions anywhere for that. Is it simply extracting the `.tgz` into `~/.webthings/addons/` and restarting?

**Comment by wfahle** [comment]
https://discourse.mozilla.org/t/newbie-question-about-missing-addons/107097/9

**Comment by arist0v** [comment]
@wfahle is there an issue since my gateway doesn'T offer me the 1.2.3 is there any issue about it, i run the default webthings image so if it'S a requirements not sure to get which requirement i'm missing!

**Comment by wfahle** [comment]
> @wfahle is there an issue since my gateway doesn'T offer me the 1.2.3 is there any issue about it, i run the default webthings image so if it'S a requirements not sure to get which requirement i'm missing!

HI @arist0v, that is a separate issue with the addon list. The 1.2.3 PR has been merged in, but for some reason doesn't show as a selection for update. Please open an issue here: https://github.com/WebThingsIO/addon-list To manually add the newest version see here: https://discourse.mozilla.org/t/newbie-question-about-missing-addons/107097/10

**Comment by arist0v** [comment]
i have no issue for manual installation, but i had taked a look at the addon list to see if there is an existing issue open but didn'T saw nothing so i wanted to ask before i was the issue :P

**Comment by arist0v** [comment]
https://github.com/WebThingsIO/addon-list/issues/1482 issue open

**Comment by arist0v** [comment]
update now available

**Comment by wfahle** [comment]
I see it too.
