### ISSUE TITLE
No module named 'ephem._libastro'

### ISSUE THREAD

**Issue by flatsiedatsie** [WTIOAddons/date-time-adapter#14]
I'm seeing this error on [Candle 2.0.2](https://www.candlesmarthome.com/download), which is essentially the Webthings Gateway running on python 3.9, but running on 64 bit Linux.

```
2023-01-31 20:06:52.702 ERROR  : date-time-adapter: Traceback (most recent call last):
2023-01-31 20:06:52.703 ERROR  : date-time-adapter:   File "/home/pi/.webthings/addons/date-time-adapter/main.py", line 13, in <module>
2023-01-31 20:06:52.704 ERROR  : date-time-adapter:     from pkg.date_adapter import DateTimeAdapter  # noqa
2023-01-31 20:06:52.706 ERROR  : date-time-adapter:   File "/home/pi/.webthings/addons/date-time-adapter/pkg/date_adapter.py", line 8, in <module>
2023-01-31 20:06:52.708 ERROR  : date-time-adapter:     from .date_device import DateTimeDevice  # , DateTimeTestDevice
2023-01-31 20:06:52.710 ERROR  : date-time-adapter:   File "/home/pi/.webthings/addons/date-time-adapter/pkg/date_device.py", line 9, in <module>
2023-01-31 20:06:52.712 ERROR  : date-time-adapter:     from .util import DT
2023-01-31 20:06:52.713 ERROR  : date-time-adapter:   File "/home/pi/.webthings/addons/date-time-adapter/pkg/util.py", line 4, in <module>
2023-01-31 20:06:52.715 ERROR  : date-time-adapter:     import ephem
2023-01-31 20:06:52.716 ERROR  : date-time-adapter:   File "/home/pi/.webthings/addons/date-time-adapter/lib/ephem/__init__.py", line 5, in <module>
2023-01-31 20:06:52.718 ERROR  : date-time-adapter:     import ephem._libastro as _libastro
2023-01-31 20:06:52.719 ERROR  : date-time-adapter: ModuleNotFoundError: No module named 'ephem._libastro'
2023-01-31 20:06:52.778 INFO   : Plugin: date-time-adapter died, code = 1 restarting after 30000
```

The folder does seem to exist:

```
pi@dev:~/.webthings/addons/date-time-adapter/lib/ephem $ ls
cities.py  doc  __init__.py  _libastro.cpython-39-arm-linux-gnueabihf.so  __pycache__  stars.py  tests
```

**Comment by wfahle** [comment]
I apologize but I have no way to test this on my pi. Is it possible the .so is the 32 bit version or something? I don't know how those shared libraries get added.

**Comment by flatsiedatsie** [comment]
Could be actually. I'll try a re-install.

**Comment by bfahle** [comment]
On linux it should either be using the linux-arm64 or linux-x64 release for the current release on this github repo. You can download it directly and copy it into your webthings-data folder.

**Comment by flatsiedatsie** [comment]
Thank you for pointing to the likely cause.

Closing this issue

**Comment by bfahle** [comment]
I will create a Candle version on a pi this weekend and try it out.

**Comment by bfahle** [comment]
Actually, you, flatsiedatsie, are a full-fledged member of this group, so you can create and merge PRs yourself if you like. Anyone else, not in this group, can create a fork and do a pull request back from that fork. We will review it and merge it if appropriate. If anyone needs a version of this that is not being built, create an issue and I will take a look (for example, wintel).
